Bring the docs to the style guide.
iotaledger/inx-participation pull request #29
Opened 2022-08-22 13:56 UTC by aleksei-korolev

2022-08-22 13:56 UTC, aleksei-korolev commented
@iotaledger/tech-writers

2022-08-22 14:26 UTC, lucas-tortora requested changes
Just 2 small changes :)

2022-08-22 14:26 UTC, lucas-tortora commented on documentation/docs/welcome.md
> +There is no dedicated structure for a voting event on the Tangle. Instead, it is represented by multiple individual transactions with certain payloads. To access the state of a voting event and the a
```suggestion
There is no dedicated structure for a voting event on the Tangle. Instead, it is represented by multiple individual transactions with specific payloads. To access the state of a voting event and the amount and distribution of the votes, you would have to find all these transactions in the Tangle and count each vote. INX-Participation does that for you: it builds a database of all voting transactions for given events and provides REST API endpoints for clients to access this information. Node operators manually select which events they wish to track.
```

2022-08-22 14:26 UTC, lucas-tortora commented on documentation/docs/welcome.md
> +There is no dedicated structure for a voting event on the Tangle. Instead, it is represented by multiple individual transactions with certain payloads. To access the state of a voting event and the a
```suggestion
There is no dedicated structure for a voting event on the Tangle. Instead, it is represented by multiple individual transactions with specific payloads. To access the state of a voting event and the amount and distribution of the votes, you would have to find all these transactions in the Tangle and count each vote. INX-Participation does that for you: it builds a database of all voting transactions for given events and provides REST API endpoints for clients to access this information. Node operators manually select which events they wish to track.
```

2022-08-22 14:26 UTC, lucas-tortora commented on documentation/docs/welcome.md
> +The participation extension connects to the running Hornet instance by default.
```suggestion
The participation extension connects to a local Hornet on http://localhost:9892 instance by default.
```
or a local hornet instance.

2022-08-23 15:41 UTC, lucas-tortora approved these changes

2022-08-23 15:46 UTC, muXxer commented on documentation/docs/welcome.md
> +There is no dedicated structure for a voting event on the Tangle. Instead, it is represented by multiple individual transactions with specific payloads. To access the state of a voting event and the
```
There is no dedicated structure for a voting event on the Tangle. Instead, it is represented by multiple individual transactions with specific payloads. To access the state of a voting event and the amount and distribution of the votes, you would have to find all these transactions in the Tangle and count each vote.```
That sounds quite negative. Can't we change that part?

2022-08-23 15:46 UTC, muXxer commented on documentation/docs/welcome.md
> +The participation extension connects to the local Hornet instance by default.
We write HORNET with capital letters almost everywhere :P

2022-08-23 16:26 UTC, lucas-tortora commented on documentation/docs/welcome.md
> +The participation extension connects to the local Hornet instance by default.
There's actually a [fair mix](https://wiki.iota.org/search?q=hornet) going around. It'd be great if we standardized this.  Seeing that the repo uses HORNET we could go with that. Though, as it's not an acronym and most other projects don't capitalize all the letters it may be confusing or look out of place. 

Personally, I'd go with normal capitalization. That being said, either works as long as we're consistent. Wdyt?

2022-08-26 12:35 UTC, aleksei-korolev commented
Since configuration.md is autogenerated, I close this pr in favor of #31

2022-08-26 12:35 UTC, closed without merging